//! Starknet contract bindings, generated by `cainome` in `build.rs`.
//!
//! The generated code lives in `OUT_DIR`, out of reach of `cargo fmt --check`.

#[allow(clippy::all, warnings)]
pub mod liquidate {
    // `cainome` hardcodes `starknet::` paths, while the crate is declared under its
    // real name `starknet-rust` so that its own macros (`::starknet_rust::…`) resolve.
    use starknet_rust as starknet;

    include!(concat!(env!("OUT_DIR"), "/liquidate.rs"));
}
